# Generated by Django 5.1.5 on 2025-06-16 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(choices=[('green_tea', 'Green Tea'), ('chocolate', 'Chocolate'), ('latte', 'Latte')], max_length=20)),
                ('add_boba', models.BooleanField(default=False)),
                ('cod', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('location', models.CharField(choices=[('idaman', 'Idaman'), ('ilham', 'Ilham'), ('impian', 'Impian'), ('psn', 'PSN'), ('surau', 'Surau'), ('cafe', 'Cafe'), ('self_pickup', 'Self-Pickup')], max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
